[package]
name = "automerge_wasi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
automerge = "0.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
